name: cadrey
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl:
  hive:
  hive_flutter:
  path_provider:
  provider:
  cupertino_icons:
  http:
  uuid:
  flutter_animated_icons: ^1.0.1
  flutter_speed_dial:
  firebase_core: ^4.2.1
  cloud_firestore: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true
  
